### ISSUE TITLE
Hackathon Reviews

### ISSUE THREAD

**Issue by alex-bellon** [rolsanmordua/waitlisters-website#11]
Have a page of hackathon reviews, which ones we really liked.

**Comment by rolsanmordua** [comment]
Establish 5 star rating system? Can simply pull rating from a column in sheets with star emojis. Then short blurb on pros, cons, highlights.

**Comment by alex-bellon** [comment]
I think the focus should be on the blurb. 5 star ratings make it seem like a competition.

**Comment by alex-bellon** [comment]
Nevermind this seems kinda useless in retrospect lol
