### ISSUE TITLE
Decide if it's Prog. Competition or Competitive Prog.

### ISSUE THREAD

**Issue by alex-bellon** [rolsanmordua/waitlisters-website#17]
The page title and header are "Competitive Programming" but the menu name and link are PC/Programming Competition.

**Comment by rolsanmordua** [comment]
I like how "competitive programming" sounds more. the _easy_ solution right now is to change it to prog. comp. because it requires the smallest change (touches the fewest parts).. but would like to see what others think.

**Comment by alex-bellon** [comment]
The gods have spoken: it's competitive programming.
